name: CI

on:
  push:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.x'

      - name: Build
        run: dotnet build

      - name: Tests
        run: dotnet test --settings tests/coverlet.runsettings --logger "trx;LogFileName=test-results.trx"

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate Code Coverage Report
        run: |
          reportgenerator \
            "-reports:**/coverage.cobertura.xml" \
            "-targetdir:coverage-report" \
            "-reporttypes:Html"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/test-results.trx'

      - name: Upload Code Coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: 'coverage-report'
